version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nextjs_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./public/uploads:/app/public/uploads
    depends_on:
      - web

volumes:
  pgdata:

