services:
  db:
    image: postgres:15
    container_name: nextjs_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  pgdata:
