version: '3'

services:
  db:
    image: postgres:15
    container_name: nextjs_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    env_file:
      - .env
    expose:
      - "3000"  # Only expose to internal network
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
