services:
  db:
    image: postgres:15
    container_name: nextjs_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    container_name: nextjs_app
    image: node:latest
    volumes:
    - ./:/app
    - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run drizzle:push && npm run dev"
    environment:
          DATABASE_URL: ${POSTGRES_URL}
          CHOKIDAR_USEPOLLING: true
    depends_on:
      - db
volumes:
  pgdata:
