name: Deploy Promo Align
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./  # repo root

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Stop any running containers
        run: docker compose down

      - name: Start Postgres
        run: docker compose up -d db

      - name: Wait for DB
        run: |
          until docker exec promo_align_db pg_isready -U $POSTGRES_USER; do
            sleep 2
          done

      - name: Run migrations inside web container
        run: docker compose run --rm web sh -c "npm install drizzle-kit --no-save && npx drizzle-kit migrate"


      - name: Build & deploy Next.js
        run: docker compose up -d --build web 