name: Deploy Promo Align

on:
  push:
    branches: [ main ]
env:
  working-directory: ./
jobs:
  migrate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_URL }}

  build-and-push:
    runs-on: self-hosted
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      - run: docker compose down
      - run: docker compose up -d --build
