name: Deploy Promo Align

on:
  push:
    branches: [ main ]
env:
  working-directory: ./
jobs:
  migrate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose down
      - run: docker compose up -d db
      - run: npm install drizzle-kit --no-save
      - run: npm run drizzle:migrate
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

  build-and-push:
    runs-on: self-hosted
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d --build web
